### PR TITLE
Link text error fix when textContent is null

### PR DESCRIPTION
**Pull request by jasonruesch**
Handled when the textContent is passed into the isDescriptiveText function as undefined or null in the link-text plugin. This fixes the error "Unable to get property 'replace' of undefined or null reference"
screen shot 2015-07-22 at 9 28 46 am

### CODE REVIEW

**Comment by jdan** [comment]
This LGTM, thank you very much!

Out of curiosity, do you have an example of a page that throws this error? I have never seen it before and it might be worth sending a fix upstream as well.

**Comment by jasonruesch** [comment]
Let me prepare one for you and I’ll send it your way shortly.

— Jason

**Comment by jasonruesch** [comment]
The error was caused by the following anchor tag:

<a href="http://localhost:50000/Learning/LearnerDefault.aspx" id="logo" class="navbar-brand navbar-logo img-responsive"></a>

As you can see, it has no text! Obviously, I’ll be fixing that in our system, but maybe the utility should’ve caught it rather than erring.

Thanks,

Jason

**Comment by jasonruesch** [comment]
Maybe the fix should be earlier in the call stack. With the fix I submitted, it gives the following help text for the error:

"The text "null" is unclear without context and may be confusing to screen readers. Consider rearranging the <a></a> tags or including special screen reader text.” The fix I’m thinking is that empty string is passed into the isDescriptiveText function instead of null from the validateTextContent function. Just a thought.

Thanks,

Jason

**Comment by jdan** [comment]
Yep, I see it, thanks!

Per the instructions in [CONTRIBUTING.md](https://github.com/Khan/tota11y/blob/master/CONTRIBUTING.md), we require contributors to sign our [Contributor License Agreement](khanacademy.org/r/cla) before we can merge their code in. If you have any questions be sure to let me know!

The fix is fine where it is - I'll likely merge this onto a separate branch and add a custom error message.

**Comment by jdan** [comment]
Landed in de2534f3e4c4675fde3dc04f279587377338f6c5.

Turns out LinkTextPlugin was getting a little stale, so I made some improvements in 34974285bab4a1b832bad878b24afe31f8efacd1 and added some unit tests in 1c86829319f60edc9e07aa0c0875c180d1961e80.

Thanks @jasonruesch! :star2:

**Pull request closed without merging**
