### PR TITLE
New webpack config (output without .min) and npm run dev

### PR DESCRIPTION
**Pull request by gbonvehi**
Modified build script to run prod (was build before) and dev which calls
webpack using a new dev config which produces a file without the .min.
suffix.

### CODE REVIEW

**Comment by gbonvehi** [comment]
This should fix #8 in the meanwhile, if someone wants an unminified version of the file, just change the build script from webpack -p to webpack -d (which is debug).

**Comment by jdan** [comment]
Thanks @gbonvehi!

Could we somehow read from `process.argv` and determine the value for `filename` that way? The repeated code here isn't too bad, but I'm wondering if we could consolidate the two configs a bit.

**Comment by jdan** [comment]
Oh and before I merge this could you also [sign the CLA](https://khanacademy.org/r/cla)?

**Comment by gbonvehi** [comment]
Sure I'll sign it. I could pass the output parameter to webpack to avoid a second config file. I'll amend that in this PR. Cheers

**Comment by gbonvehi** [comment]
Hi @jdan I signed the CLA, removed the extra webpack.config and merged your latest changes into the PR.
Cheers,
Guillermo

**Comment by jdan** [comment]
Awesome, thank you!

I see this also generates a `.map`, should I be checking that into version control as well? Maybe for now we don't need it?

**Comment by jdan** [comment]
Looks like this is being added to the footer:

```
// SCRIPT-LOADER FOOTER
//# sourceURL=script:///Users/jordan/Projects/tota11y/node_modules/accessibility-developer-tools/dist/js/axs_testing.js
```

Why won't be too helpful if we host this anywhere.

**Comment by gbonvehi** [comment]
It's optional, some will use it. most won't, I think is better to leave it off by default, advanced users can generate it anyways if needed.

**Comment by jdan** [comment]
Thanks for the quick turnaround. Just pulled the changes down and everything looks good - thanks for taking this on :star2:

**Pull request merged**
