### PR TITLE
Experimental plugins

### PR DESCRIPTION
**Pull request by jdan**
Hey @MichelleTodd `||` @rileyjshaw!

I keep toying with JSX, and decided to work on top of #46 to build the concept of "Experimental" plugins into the UI. We'll use this for #44!

No experimental plugins yet, so nothing will actually look different, but here's what renders when we *will* have experimental plugins.

image

Also included is a change to our JSX transpile target which allows us to do things like `<Plugin ... />`. It just looks cool :)

### CODE REVIEW

**Comment by rileyjshaw** [comment]
> ... `<Plugin ... />`

ouuuuuu prettyyyy

**Comment by spicyj** [comment]
Those who don't understand ~~LISP~~ ~~UNIX~~ React are doomed to reinvent it? :D

**Comment by jdan** [comment]
We'll see how far this crazy train can go. Expect a virtual dom by next week.

**Comment by spicyj** [comment]
Yuck.

https://twitter.com/sebmarkbage/status/530393349069750272

**Comment by spicyj** [comment]
:)

**Pull request merged**
