### PR TITLE
Add confirmation message in panel for no errors case

### LINKED ISSUE #13: Missing some sort of "confirmation" for 0 errors, empty summary
http://jordanscales.com/

image

"Headings" produces an empty summary. Clicking "Labels" does, well, nothing. Expected because there are no inputs, but maybe a little strange.

### PR DESCRIPTION
**Pull request by ankitaggarwal011**
Fix #13. What do you think? @jdan

### CODE REVIEW

**Comment by jdan** [comment]
I'll check this out later in the afternoon, but what happens with the Landmarks plugin?

**Comment by ankitaggarwal011** [comment]
@jdan ,this is just another check in shared info-panel to check for 0 errors case and add a confirmation message in error tab when there are no errors. This will work with all the plugins since info-panel is shared among all plugins. I had added Landmarks plugin image in issue #13 just as an example. Thanks!

**Comment by jdan** [comment]
@ankitaggarwal011 my concern is that Landmarks will never have errors though, as it's a plugin that reports errors. We'll have others like this like a color blindness simulator.

**Comment by ankitaggarwal011** [comment]
I understand your concern now. But still I think, even in cases such as Landmarks, it's better than displaying a confusing blank panel (current scenario). This doesn't require a lot changes in plugin architecture.

I can think of a few solutions for this problem:
* Don't display panels for Landmarks and similar plugins. This can be done adding a new variable to check for non-error plugins.
* Add a new variable to hide/show panel with each plugin settings.

Though, both of these solutions would require changing in the plugin architecture.
What do you think? @jdan.

**Comment by jdan** [comment]
Landmarks won't display a blank panel, only Headings does - and that's because the summary is empty, but still triggers the info panel. Errors aren't the issue here - our conversation seems to have forked a little.

A fix for #13 involves simply fixing the logic to not render an info panel if summary is empty. I think we should deal with the "confirmation if no errors" part separately, since it requires some more thought. Does that make sense?

So I'll close this PR because I'm reluctant to merge anything dealing with "confirmation" right now.

**Comment by ankitaggarwal011** [comment]
@jdan , Yeah sure, no worries. 
Yeah, I guess the discussion has diverged a bit, but the issue is still isn't solved yet. You may want to look at it again later. Maybe you can keep it at a lower priority is issue list. 
But I want to state that there is one core issue at hand here:
* One where there is no confirmation in case of 0 errors. This is the case for all of the plugins, not just Headings plugin. In landmarks and similar plugins, nothing is shown on the screen for no errors and for heading and similar plugins, empty summary is shown for no errors.

I was trying to address this core issue by showing a confirmation of 0 errors in all the cases.
There are also better ways to address this issue by generalizing plugin creation as I mentioned in the last comment. I believe you should incorporate an endpoint in plugin creation regarding this before you move on to the standard release as it could be an important issue as your plugin list grows.
Thanks for looking into it!

**Pull request closed without merging**
