### PR TITLE
Steps to make tota11y more screen-reader friendly and keyboard-accessible

### LINKED ISSUE #47: tota11y needs keyboard and screen reader accessibility
I was excited to try tota11y, but the tool itself is actually not accessible via keyboard or speech recognition. Technically it can be used via a screen reader, but realistically it would be almost impossible to use via screen reader without being able to see. (It doesn't make any announcements on dynamic updates, and checking a box to open up a flag on inaccessible content doesn't move the focus to the new content warning, making it almost impossible for the screen reader user to find the newly-opened warning box.)

This is important to fix for two reasons:
* many accessibility professionals (and many web professionals in general) are disabled and use assistive technology, and
* if you are trying to showcase how easy it is to fix a product to make it accessible, it would be really wonderful if your product showed off accessibility.

Thanks for building the tool and  thanks for caring about accessibility!

### PR DESCRIPTION
**Pull request by jdan**
This PR adds several features to make tota11y more keyboard and screen-reader friendly, notably:

* Adding keyboard toggling to the list of plugins (and a focus indicator)
* Adding screen reader text to the toolbar expand button, close buttons in the info panel, and "scroll to error" buttons in the info panel entries
* When activating a plugin, focus is directed to the newly-created info panel
* Menu aria roles on the list of plugins

I am still struggling to make annotations screen reader friendly, as they are located near the errors to sighted users, but for screen readers there is no strong connection. I am thinking that the "Scroll to error" button can be repurposed to *focus* the violating element.

@rileyjshaw || @MichelleTodd - would you mind reviewing the code in this diff? a11y-wise, I'll keep exploring more options, but this is definitely a step in the right direction.

### CODE REVIEW

**Comment by rileyjshaw** [comment]
(Sorry that I haven't gotten to this yet - I can check it out by the end of the week if that's okay?)

**Comment by jdan** [comment]
Yeah no huge rush here. It's a big scary diff but there isn't *that* much going on. Mainly moving handlebars -> JSX (maybe that should be its own diff)

**Comment by MichelleTodd** [comment]
all of this looks good to me! thank you for splitting your code up into such small & well-defined commits! :D

**Comment by rileyjshaw** [comment]
Woohooooooo jsx!!

Just took a peek at this, looks cool :)

**Pull request merged**
