### PR TITLE
Fix bookmarklet button url

### PR DESCRIPTION
**Pull request by richardwestenra**
The href url for the [bookmarklet button](http://khan.github.io/tota11y/#Installation) doesn't work: It's currently set to "#" but it should probably be something like this:

    javascript:(function(){var%20tota11y=document.createElement('SCRIPT');tota11y.type='text/javascript';tota11y.src='http://khan.github.io/tota11y/tota11y/build/tota11y.min.js';document.getElementsByTagName('head')[0].appendChild(tota11y);})();

### CODE REVIEW

**Comment by jdan** [comment]
This was my mistake, the button has `href="#"` when the document loads, but that `href` is changed in `script.js` to inline the entire contents of `tota11y.min.js`. Because I changed the location of `tota11y.min.js` yesterday, it's broken.

I like your solution of creating the script tag with a source. Do you know how reliable it is to serve static files from a github repo? I've heard stories of projects getting rate-limited, but perhaps the times have changed.

**Comment by richardwestenra** [comment]
I haven't heard of projects getting rate-limited. I know you're not supposed to serve raw.githubusercontent.com or rawgit.com files in production, but I double that there'd be a problem with Github Pages files.

Cheers!

**Comment by jdan** [comment]
That's a good point - serving from gh-pages shouldn't be a problem :+1: 

Could you also remove the existing code to populate the href in `script.js`? And make sure you've [signed the CLA](https://github.com/Khan/tota11y/blob/master/CONTRIBUTING.md#cla) so I can merge this in.

Thanks again, this helps so much,
Jordan

**Comment by richardwestenra** [comment]
Sure, done and done. I assume you still wanted the bookmarklet hidden in non-webkit browsers?

**Comment by jdan** [comment]
Nope! No need since the href is much shorter, this should work fine everywhere.



--



jordan scales

http://jordanscales.com

**Comment by richardwestenra** [comment]
Ah okay. I'll remove that too.

**Comment by jdan** [comment]
Thanks for signing the CLA. There are some merge conflicts because I updated that segment of code earlier to get the bookmarklet up and running. Mind rebasing off `gh-pages`? Happy to assist you in doing so.

**Comment by jdan** [comment]
Merged into `gh-pages` via 9475894ed83e59aaa99dd5e4292ae3c5ab1f4683, d80a53f4cad30eec83d3c4684fa9c620111f4cae, and 13fd3935be095652d174ab0e73f9f72df6dd8f4e. I also added 71235ad1a3efea46f88f4ede9e3e3495a6fb8e7d to remove the `http://` part of the url so the bookmarklet would work on https:// sites.

Thanks again Richard! This is a big improvement.

**Pull request closed without merging**
