### PR TITLE
bump accessibility-developer-tools

### PR DESCRIPTION
**Pull request by ibroadfo**

### CODE REVIEW

**Comment by jdan** [comment]
Thanks for this @ibroadfo! ADT has some really nifty stuff in this version.

As the super polite robot pointed out, would you mind giving our CLA a sign? Also it looks like #110 caused a merge conflict in package.json :( Happy to answer any questions you may have.

**Comment by ibroadfo** [comment]
[clabot:check]

**Comment by jdan** [comment]
[clabot:check]

**Comment by jdan** [comment]
Thanks so much @ibroadfo ✨ Just merged into master.

**Pull request merged**
